#!/usr/bin/env bash
# One-shot Android APK build. Produces a debug-signed, installable APK at the repo root.
# It does NOT install any toolchain — you must already have (see GUIDE.md §6.1):
#   • Android SDK + build-tools 36 + platform 36 + ndk;27.1.12297006 + cmake;3.22.1
#   • a local JDK 17 (for the Gradle toolchain; JDK 21 alone fails on Gradle 9 / Foojay)
#
#   export ANDROID_HOME=$HOME/android-sdk
#   export JAVA17_HOME=/path/to/jdk17
#   ./build-apk.sh                 # ABI=arm64-v8a by default; set ABI= for a universal build
set -euo pipefail
cd "$(dirname "$0")"
: "${ANDROID_HOME:?set ANDROID_HOME to your Android SDK dir}"
: "${JAVA17_HOME:?set JAVA17_HOME to a JDK 17 install (for the Gradle toolchain)}"
ABI="${ABI:-arm64-v8a}"
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

cd client
# generate the native project if missing (android/ is gitignored / regenerated by prebuild)
[ -f android/gradlew ] || npx expo prebuild -p android --no-install

# SDK path + JDK17 toolchain config (idempotent — android/ is regenerated by prebuild)
[ -f android/local.properties ] && grep -q '^sdk.dir=' android/local.properties || echo "sdk.dir=$ANDROID_HOME" > android/local.properties
if ! grep -q 'org.gradle.java.home' android/gradle.properties; then
  {
    echo ""
    echo "# Run Gradle ON JDK 17 (RN jvmToolchain(17)); avoids the Gradle-9 Foojay/IBM_SEMERU crash."
    echo "org.gradle.java.home=$JAVA17_HOME"
    echo "org.gradle.java.installations.auto-download=false"
  } >> android/gradle.properties
fi

cd android
echo "Building release APK ($ABI)…"
./gradlew :app:assembleRelease -PreactNativeArchitectures="$ABI" --no-daemon "$@"

APK="app/build/outputs/apk/release/app-release.apk"
OUT="territorial-v1.0.0-$ABI.apk"
cp "$APK" "../../$OUT"
echo "✅ APK → $(cd ../.. && pwd)/$OUT   (debug-signed, installable via: adb install $OUT)"
